// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9WWMjYs2gyQXMvMAkxbjFX
// Component: KWpY_ILPfCi6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: WvItauIVw1SL/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_app_starter.module.css"; // plasmic-import: 9WWMjYs2gyQXMvMAkxbjFX/projectcss
import sty from "./PlasmicLogoutButton.module.css"; // plasmic-import: KWpY_ILPfCi6/css

import AppleIcon from "./icons/PlasmicIcon__Apple"; // plasmic-import: BoW0iYMM00Da/icon

createPlasmicElementProxy;

export type PlasmicLogoutButton__VariantMembers = {};
export type PlasmicLogoutButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogoutButton__VariantsArgs;
export const PlasmicLogoutButton__VariantProps = new Array<VariantPropType>();

export type PlasmicLogoutButton__ArgsType = {};
type ArgPropType = keyof PlasmicLogoutButton__ArgsType;
export const PlasmicLogoutButton__ArgProps = new Array<ArgPropType>();

export type PlasmicLogoutButton__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
  logoutBtn?: p.Flex<typeof Button>;
  loginBtn?: p.Flex<typeof Button>;
};

export interface DefaultLogoutButtonProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogoutButton__RenderFunc(props: {
  variants: PlasmicLogoutButton__VariantsArgs;
  args: PlasmicLogoutButton__ArgsType;
  overrides: PlasmicLogoutButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      {(() => {
        try {
          return currentUser.isLoggedIn;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div className={classNames(projectcss.all, sty.freeBox__wiOa5)}>
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return `Hi ${currentUser.email}`;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <Button
            data-plasmic-name={"logoutBtn"}
            data-plasmic-override={overrides.logoutBtn}
            className={classNames("__wab_instance", sty.logoutBtn)}
          >
            {"Logout"}
          </Button>
        </div>
      ) : null}
      {(() => {
        try {
          return !currentUser.isLoggedIn;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div className={classNames(projectcss.all, sty.freeBox___3HVy0)}>
          <Button
            data-plasmic-name={"loginBtn"}
            data-plasmic-override={overrides.loginBtn}
            className={classNames("__wab_instance", sty.loginBtn)}
          >
            {"Login"}
          </Button>
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text", "logoutBtn", "loginBtn"],
  text: ["text"],
  logoutBtn: ["logoutBtn"],
  loginBtn: ["loginBtn"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
  logoutBtn: typeof Button;
  loginBtn: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogoutButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogoutButton__VariantsArgs;
    args?: PlasmicLogoutButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLogoutButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLogoutButton__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogoutButton__ArgProps,
          internalVariantPropNames: PlasmicLogoutButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogoutButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogoutButton";
  } else {
    func.displayName = `PlasmicLogoutButton.${nodeName}`;
  }
  return func;
}

export const PlasmicLogoutButton = Object.assign(
  // Top-level PlasmicLogoutButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    logoutBtn: makeNodeComponent("logoutBtn"),
    loginBtn: makeNodeComponent("loginBtn"),

    // Metadata about props expected for PlasmicLogoutButton
    internalVariantProps: PlasmicLogoutButton__VariantProps,
    internalArgProps: PlasmicLogoutButton__ArgProps
  }
);

export default PlasmicLogoutButton;
/* prettier-ignore-end */
